- name: Install Apache Skywalking
  hosts: ["opensearch"]
  become: true
  vars:
    java_bin_path: /usr/lib/jvm/jdk-17-oracle-x64/bin/java
    oracle_java_version: 17
  roles: 
    - role: dimmaryanto93.oracle_java
    - role: dimmaryanto93.opensearch