- name: Install Nexus OSS
  hosts: ["nexus-oss"]
  vars:
    nexus_username: admin # changed the user name of your nexus username cred
    nexus_password: passwordnyaR00t # change the password of your nexus password cred
    nexus_create_new_user: true # set true if you want create an other user
    nexus_new_user: test # change this username for new user
    nexus_new_user_pass: test # change this password for new user
  roles: 
    - role: dimmaryanto93.sonatype_nexus_oss_registry