stages:
  - deploy-ias-review
  - deploy-ias-production

include:
  - local: 'templates/gitops-flow.gitlab-ci.yml'
  - local: '.gitlab/agents/review/.gitlab-ci.yml'
  - local: '.gitlab/agents/production/.gitlab-ci.yml'

