apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

components:
  - ../../components/nginx-community-ingress

patches:
  - target:
      kind: Service
      name: ingress-nginx-controller
      namespace: ingress-nginx
    path: service.yaml
