stages:
  - pre-build
  - test
  - build

variables:
  MAVEN_JDK_VERSION: "3.8-openjdk-18"

include:
  - remote: https://raw.githubusercontent.com/dimMaryanto93/gitlab-devops-automation/gitlab-kas/templates/build.maven.gitlab-ci.yml
  - remote: https://raw.githubusercontent.com/dimMaryanto93/gitlab-devops-automation/gitlab-kas/templates/build.docker.gitlab-ci.yml


get-fact:project-metadata:
  extends: .gitlab-registry-get-fact-project-info
  stage: pre-build

test:junit:
  stage: test
  extends: .gitlab-registry-test-junit
  allow_failure: true

build:jar:
  stage: build
  extends: .gitlab-registry-build-jar
  needs:
    - get-fact:project-metadata

build:docker:x64-linux:
  stage: build
  extends: .docker-registry-build-docker
  variables:
    DOCKER_BUILD_ARGS_ENTRIPOINT: "--build-arg JAR_FILE=$JAR_FILE"
  needs:
    - get-fact:project-metadata
    - build:jar

