apiVersion: v1
kind: Secret
metadata:
  name: ntnx-files-secret
  namespace: ntnx-system
data:
  # Provide Nutanix Prism Element credentials which is a default UI credential separated by colon in "key:".
  ## prism-element-ip:prism-port:admin:password
  key: 'MTAuMzguMTg3LjM3Ojk0NDA6YWRtaW46bngyVGVjaDA3MSE='
  # Provide Nutanix File Server credentials which is a REST API user created on File server UI separated by colon in
  ## nutanix-files:rest-api-user:password.
  files-key: "ZGMubnRueGxhYi5sb2NhbDpudG54LWFwaTpueDJUZWNoMDcxIQ=="