apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - namespace.yaml

patches:
  - path: service.yaml
    target:
      kind: Service
      name: springboot-app

namespace: api
