apiVersion: v1
kind: Service
metadata:
  name: springboot-app
  labels:
    app: siapbos-auth
spec:
  selector:
    app: springboot-app
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 32003
  type: NodePort
