- name: Modify file /etc/hosts to add inventory ip
  hosts: ["all"]
  become: true
  tasks:
    - name: Add IP address of all hosts to all hosts
      lineinfile:
        dest: /etc/hosts
        line: "{{ hostvars[item].ansible_host }} {{ hostvars[item].inventory_hostname }}"
        state: present
      with_items: "{{ groups.all }}"

