gitops:
  manifest_projects:
    - paths:
        - glob: '.kube/*.yaml'
      reconcile_timeout: 3600s
      dry_run_strategy: none
      prune: true
      prune_timeout: 3600s
      prune_propagation_policy: foreground
      inventory_policy: must_match
ci_access:
  projects:
    - id: examples/gitlab-ci-cd/gitlab-kas-cicd-example:testing