apiVersion: v1
kind: ConfigMap
metadata:
  name: siapbos-api
data:
  DATABASE_HOST: "127.0.0.1"
  DATABASE_PORT: "5432"
  DATABASE_USER: "example"
  DATABASE_PASSWORD: "example"
  DATABASE_NAME: "example"
  FLYWAY_ENABLED: "true"
