apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base
  - configmap-db.yaml
  - deployment.yaml
  - service.yaml

commonLabels:
  tier: backend

patches:
  - path: configmap-base.yaml
    target:
      kind: ConfigMap
      name: base-config
