apiVersion: v1
kind: Service
metadata:
  name: siapbos-api
  labels:
    app: siapbos-auth
spec:
  selector:
    app: siapbos-api
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  type: ClusterIP
