deploy-cert-manager:prod:
  stage: deploy-ias-production
  when: manual
  variables:
    GIT_REMOTE_BRANCH: production-env
    KUBERNETES_MANIFEST_TEMPLATES:
      kubernetes/components/cert-manager
  environment:
    name: production
  extends: .kustomize-build
  resource_group: deploy/review

deploy-k8s-dashboard:prod:
  stage: deploy-ias-production
  when: manual
  variables:
    GIT_REMOTE_BRANCH: production-env
    KUBERNETES_MANIFEST_TEMPLATES:
      kubernetes/components/kubernetes-dashboard
  environment:
    name: production
  extends: .kustomize-build
  resource_group: deploy/review

deploy-metrics-server:prod:
  stage: deploy-ias-production
  when: manual
  variables:
    GIT_REMOTE_BRANCH: production-env
    KUBERNETES_MANIFEST_TEMPLATES:
      kubernetes/components/metrics-server
  environment:
    name: production
  extends: .kustomize-build
  resource_group: deploy/review

deploy-metrics-server:prod:
  stage: deploy-ias-production
  when: manual
  variables:
    GIT_REMOTE_BRANCH: production-env
    KUBERNETES_MANIFEST_TEMPLATES:
      kubernetes/components/metrics-server
  environment:
    name: production
  extends: .kustomize-build
  resource_group: deploy/review

deploy-metallb:prod:
  stage: deploy-ias-production
  when: manual
  variables:
    GIT_REMOTE_BRANCH: production-env
    KUBERNETES_MANIFEST_TEMPLATES:
      kubernetes/components/metallb
  environment:
    name: production
  extends: .kustomize-build
  resource_group: deploy/review
