gitlab_host             ansible_port=22 ansible_user=admin ansible_host=10.12.10.50
gitlab-runner01_host    ansible_port=22 ansible_user=admin ansible_host=10.12.10.51
nexus-oss_host          ansible_port=22 ansible_user=admin ansible_host=10.12.10.55
sonarqube_host          ansible_port=22 ansible_user=admin ansible_host=10.12.10.56
jmeter_host             ansible_port=22 ansible_user=admin ansible_host=10.12.10.57

[gitlab]
gitlab_host

[gitlab-runner]
gitlab-runner01_host

[nexus-oss]
nexus-oss_host

[sonarqube]
sonarqube_host

[jmeter]
jmeter_host