apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: springboot-app
  labels:
    app: springboot-app
spec:
  maxReplicas: 5
  minReplicas: 1
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80

  scaleTargetRef:
    kind: Deployment
    name: springboot-app
    apiVersion: apps/v1
