---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: springboot-log-storage
spec:
  capacity:
    storage: 500Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /logging
    server: 10.55.22.48