apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-springboot3-logging
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
  volumeMode: Filesystem
  volumeName: springboot-log-storage
