kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: nutanix-s3-sc
provisioner: ru.yandex.s3.csi
parameters:
  mounter: geesefs
  # you can set mount options here, for example limit memory cache size (recommended)
  options: "--memory-limit 1000 --dir-mode 0777 --file-mode 0666"
  # to use an existing bucket, specify it here:
  bucket: bank-muamalat
  csi.storage.k8s.io/provisioner-secret-name: ntnx-s3-secret
  csi.storage.k8s.io/provisioner-secret-namespace: ntnx-s3
  csi.storage.k8s.io/controller-publish-secret-name: ntnx-s3-secret
  csi.storage.k8s.io/controller-publish-secret-namespace: ntnx-s3
  csi.storage.k8s.io/node-stage-secret-name: ntnx-s3-secret
  csi.storage.k8s.io/node-stage-secret-namespace: ntnx-s3
  csi.storage.k8s.io/node-publish-secret-name: ntnx-s3-secret
  csi.storage.k8s.io/node-publish-secret-namespace: ntnx-s3